apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: availability-notify
  annotations:
    github.com/project-slug: vtex-apps/availability-notify
spec:
  type: other
  lifecycle: unknown
  owner: te-0013
